# Generated by Django 6.0.4 on 2026-04-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_is_superhost', models.BooleanField()),
                ('host_total_listings_count', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accommodates', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('extra_people', models.FloatField()),
                ('minimum_nights', models.IntegerField()),
                ('number_of_reviews', models.IntegerField()),
                ('instant_bookable', models.BooleanField()),
                ('num_amenities', models.IntegerField()),
                ('preco_previsto', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
